### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by yadoga** [mskocik/svelecte#300]
Seemingly an issue appeared with svelecte 5.2.0 and Svelte 5.35.0 compatibility:

```
x Build failed in 4.24s
error during build:
[vite:build-import-analysis] [plugin vite:build-import-analysis] node_modules/.pnpm/svelecte@5.2.0_svelte@5.35.0/node_modules/svelecte/dist/Svelecte.svelte (1856:0): Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
file: /Users/[...]/node_modules/.pnpm/svelecte@5.2.0_svelte@5.35.0/node_modules/svelecte/dist/Svelecte.svelte:1856:0

1854:
1855:   $.pop();
1856: }
      ^
1857: import "/Users/[...]/node_modules/.pnpm/svelecte@5.2.0_svelte@5.35.0/node_modules/svelecte/dist...
```

**Comment by yadoga** [comment]
Downgrading to Svelte 5.16.0 resolved the syntax error with svelecte.

**Comment by sp00m** [comment]
Passes with Svelte 5.34.9 too, I believe the issue occurs with 5.35+.

EDIT: since 5.35, [esrap](https://github.com/sveltejs/esrap) has been bumped to v2, see https://github.com/sveltejs/svelte/pull/16240. Not super familiar with this lib, but v2 brings breaking changes apparently: https://github.com/sveltejs/esrap/releases/tag/v2.0.0.

**Comment by microdou** [comment]
I encountered the same issue with `svelte 5.35.0`. Works on `svelte 5.34.9`.

I forked the source files from `src/lib` and it works with `svelte 5.35.0`.
I believe a simple bump of `svelte` from `5.2.7` to a higher version (`5.35.0`) in `peerDependencies` of `package.json` may resolve the issue.

**Comment by Neptunium1129** [comment]
https://github.com/sveltejs/svelte/issues/16292 
I've reported the issue. It may take a little while.

**Comment by Neptunium1129** [comment]
> Passes with Svelte 5.34.9 too, I believe the issue occurs with 5.35+.
> 
> EDIT: since 5.35, [esrap](https://github.com/sveltejs/esrap) has been bumped to v2, see [sveltejs/svelte#16240](https://github.com/sveltejs/svelte/pull/16240). Not super familiar with this lib, but v2 brings breaking changes apparently: https://github.com/sveltejs/esrap/releases/tag/v2.0.0.

Svelte 5.34.9 is working! But the current version 5.35.1 has a problem.

**Comment by mskocik** [comment]
Has anybody tried it with svelte 5.32.2? It should fix that issue.

**Comment by sp00m** [comment]
Correct, 5.32.2 fixed it on my side 👍

**Comment by NickMous** [comment]
I still have an issue, sadly. 

```
 error  in /var/www/html/version2/tsconfig.json

[tsl] ERROR
      TS2688: Cannot find type definition file for 'minimatch'.
  The file is in the program because:
    Entry point for implicit type library 'minimatch'
```

Don't know if it's related to svelecte, but earlier, before 5.23.2, it showed the same code snippet as the original issue has

**Comment by mskocik** [comment]
I would say it must be related to svelte itself. Lib hasn't been changed in a while. Try to update to the latest svelte to see, if the issue disappears

**Comment by NickMous** [comment]
We've solved it by pinning @types/minimatch to v3, for some reason with the packages we had, there were 10 different versions installed
